services:

  zafiria-db:
    image: postgres:15
    container_name: zafiria-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zafiria_user
      POSTGRES_PASSWORD: Zafiria2026
      POSTGRES_DB: zafiria_db
    ports:
      - "5455:5432"
    volumes:
      - zafiria-pgdata:/var/lib/postgresql
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zafiria_user"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - zafiria-net

  zafiria-auth:
    image: quay.io/keycloak/keycloak:23.0
    container_name: zafiria-auth
    restart: on-failure:2
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://zafiria-db:5432/keycloak_db
      KC_DB_USERNAME: zafiria_user
      KC_DB_PASSWORD: Zafiria2026
      KC_DB_SCHEMA: public
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Zafiria2026
      KC_LOG_LEVEL: INFO
    ports:
      - "8910:8080"
    volumes:
      - zafiria-kcdata:/opt/keycloak/data
      - ./keycloak/zafiria-realm.json:/opt/keycloak/data/import/zafiria-realm.json:ro
    depends_on:
      zafiria-db:
        condition: service_healthy
    command: start-dev --import-realm
    networks:
      - zafiria-net

  zafiria-api:
    build:
      context: .
      dockerfile: Zafiria.API/Dockerfile
    container_name: zafiria-api
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=zafiria-db;Port=5432;Database=zafiria_db;Username=zafiria_user;Password=Zafiria2026
      Keycloak__Authority: http://zafiria-auth:8080/realms/zafiria-realm
      Keycloak__Audience: zafiria-api
      Keycloak__ClientId: zafiria-api
      Keycloak__ClientSecret: zWNEnhX7R1mNISxhuF6RvKNtWBk9z9Dp
    ports:
      - "5025:8080"
    depends_on:
      zafiria-db:
        condition: service_healthy
      zafiria-auth:
        condition: service_started
    networks:
      - zafiria-net

  zafiria-front:
    build:
      context: ../zafiria-front
      dockerfile: Dockerfile
    container_name: zafiria-front
    environment:
      API_URL: http://zafiria-api:8080
      KEYCLOAK_URL: http://zafiria-auth:8080
    ports:
      - "4200:80"
    depends_on:
      - zafiria-api
    networks:
      - zafiria-net

networks:
  zafiria-net:
    driver: bridge

volumes:
  zafiria-pgdata:
  zafiria-kcdata: