// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zafiria.Infrastructure.Data;

#nullable disable

namespace Zafiria.Infrastructure.Migrations
{
    [DbContext(typeof(ZafiriaDbContext))]
    [Migration("20260329215443_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zafiria.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Joyas para mujeres",
                            Nombre = "Mujeres"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Joyas para niños",
                            Nombre = "Niños"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Joyas para varones",
                            Nombre = "Varones"
                        });
                });

            modelBuilder.Entity("Zafiria.Core.Entities.ImagenJoya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JoyaId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JoyaId");

                    b.ToTable("ImagenesJoya");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Joya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OcasionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("OcasionId");

                    b.ToTable("Joyas");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Ocasion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ocasiones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Joyas para bodas",
                            Nombre = "Boda"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Joyas para bautizos",
                            Nombre = "Bautizo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Joyas para graduaciones",
                            Nombre = "Graduacion"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Joyas para compromisos",
                            Nombre = "Compromiso"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Joyas para profesionales",
                            Nombre = "Profesion"
                        });
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JoyaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JoyaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.ImagenJoya", b =>
                {
                    b.HasOne("Zafiria.Core.Entities.Joya", "Joya")
                        .WithMany("Imagenes")
                        .HasForeignKey("JoyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joya");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Joya", b =>
                {
                    b.HasOne("Zafiria.Core.Entities.Categoria", "Categoria")
                        .WithMany("Joyas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zafiria.Core.Entities.Ocasion", "Ocasion")
                        .WithMany("Joyas")
                        .HasForeignKey("OcasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Ocasion");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Reserva", b =>
                {
                    b.HasOne("Zafiria.Core.Entities.Joya", "Joya")
                        .WithMany("Reservas")
                        .HasForeignKey("JoyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joya");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Joyas");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Joya", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Zafiria.Core.Entities.Ocasion", b =>
                {
                    b.Navigation("Joyas");
                });
#pragma warning restore 612, 618
        }
    }
}
